name: Code Coverage
on:
  pull_request:
  push:
    branches:
      - master

steps:
  - uses: actions/checkout@master
  - uses: codecov/codecov-action@v3
    with:
      directory: ./coverage
      flags: e2e
      fail_ci_if_error: true
      verbose: true