name: Code Coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          flags: e2e
          fail_ci_if_error: true
          verbose: true