name: Unit tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v3
      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies 🛠️
        run: npm i
      - name: Run Vitest 🧪
        run: npx vitest run --silent